import mongoose, { Types } from 'mongoose';
import { Category } from '../models/Category.model';
import { Product } from '../models/Product.model';
import { User } from '../models/User.model';
import { connectDB } from './db';
import { logger } from './logger';
import { ProductStatus } from './constants';

interface ProductSeedItem {
  slug: string;
  canonicalDomain: string;
  name: string;
  tagline: string;
  description: string;
  websiteUrl: string;
  categorySlug: string;
  pricing: {
    model: 'free' | 'freemium' | 'paid' | 'open_source';
    startingPrice?: number;
    currency?: string;
  };
  logoUrl: string;
  screenshotUrls: string[];
  daysAgo: number;
}

export const CURATED_100_PRODUCTS: ProductSeedItem[] = [
  // ===================== AI TOOLS (15 Products) =====================
  {
    slug: 'promptcanvas',
    canonicalDomain: 'promptcanvas.io',
    name: 'PromptCanvas',
    tagline: 'Visual node-based IDE for building and versioning production LLM chains',
    description: 'The standard visual workspace for AI engineers. Drag-and-drop prompt chaining, real-time token economics inspection, and automated unit testing suites.',
    websiteUrl: 'https://promptcanvas.io',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 20 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 0,
  },
  {
    slug: 'neuralscribe',
    canonicalDomain: 'neuralscribe.ai',
    name: 'NeuralScribe',
    tagline: 'AI copilot for technical documentation and engineering runbooks',
    description: 'Autonomous documentation engine that scans GitHub commits and PR diffs to maintain real-time architecture diagrams and API references.',
    websiteUrl: 'https://neuralscribe.ai',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'speechcraft-ai',
    canonicalDomain: 'speechcraft.audio',
    name: 'SpeechCraft AI',
    tagline: 'Hyper-realistic neural voice synthesis with multilingual emotional modulation',
    description: 'Ultra-low latency text-to-speech API with sub-100ms voice cloning and expressive cadence control for podcasts, audiobooks, and interactive agents.',
    websiteUrl: 'https://speechcraft.audio',
    categorySlug: 'ai-tools',
    pricing: { model: 'paid', startingPrice: 29 },
    logoUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'visionary-lens',
    canonicalDomain: 'visionarylens.ai',
    name: 'VisionaryLens',
    tagline: 'Multi-modal computer vision API for high-speed industrial object detection',
    description: 'Fine-tuned zero-shot object detection and segmentation framework built for factory robotics, video inspection, and spatial computing.',
    websiteUrl: 'https://visionarylens.ai',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 49 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'codewhisper-studio',
    canonicalDomain: 'codewhisper.dev',
    name: 'CodeWhisper Studio',
    tagline: 'AI pair programmer with zero-trust local model execution',
    description: 'Privacy-focused code intelligence extension running quantized LLMs entirely on developer hardware with zero telemetry leaks.',
    websiteUrl: 'https://codewhisper.dev',
    categorySlug: 'ai-tools',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'deepsummary-ai',
    canonicalDomain: 'deepsummary.co',
    name: 'DeepSummary AI',
    tagline: 'Summarize 100-page academic papers and legal briefs in under 5 seconds',
    description: 'Cross-document factual consistency checker and hierarchical research summarizer with verified bibliographic citation attribution.',
    websiteUrl: 'https://deepsummary.co',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 12 },
    logoUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'datamorph-ai',
    canonicalDomain: 'datamorph.io',
    name: 'DataMorph AI',
    tagline: 'Transform messy unformatted data into clean relational JSON schemas',
    description: 'Schema-aware tabular intelligence engine that extracts, cleans, and standardizes enterprise CSV, PDF, and scan dumps automatically.',
    websiteUrl: 'https://datamorph.io',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 35 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'contextflow-ai',
    canonicalDomain: 'contextflow.tech',
    name: 'ContextFlow',
    tagline: 'Long-context memory indexing system for real-time generative agents',
    description: 'Episodic memory store and hybrid vector-lexical retrieval pipeline providing infinite context retention for conversational models.',
    websiteUrl: 'https://contextflow.tech',
    categorySlug: 'ai-tools',
    pricing: { model: 'paid', startingPrice: 40 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'audioextract-pro',
    canonicalDomain: 'audioextract.ai',
    name: 'AudioExtract Pro',
    tagline: 'Split instrumentals, vocals, and sound effects with zero acoustic artifacts',
    description: 'Deep neural stem separation engine for music producers, video editors, and audio cleanup teams.',
    websiteUrl: 'https://audioextract.ai',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'synthavatar',
    canonicalDomain: 'synthavatar.video',
    name: 'SynthAvatar',
    tagline: 'Photorealistic AI video presenters for corporate training and demos',
    description: 'Generate high-definition talking avatar video lessons from markdown scripts in over 40 languages without camera hardware.',
    websiteUrl: 'https://synthavatar.video',
    categorySlug: 'ai-tools',
    pricing: { model: 'paid', startingPrice: 49 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'docuchat-ai',
    canonicalDomain: 'docuchat.cloud',
    name: 'DocuChat AI',
    tagline: 'Chat with compliance manuals and enterprise SOC2 policies',
    description: 'Enterprise-grade RAG workspace with strict permission gates, SOC2 compliance, and audit log generation.',
    websiteUrl: 'https://docuchat.cloud',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 25 },
    logoUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'promptpilot',
    canonicalDomain: 'promptpilot.app',
    name: 'PromptPilot',
    tagline: 'Automated prompt regression testing and hallucination benchmark suite',
    description: 'CI/CD pipeline step that catches semantic drift and prompt degradations across OpenAI, Anthropic, and open-source models.',
    websiteUrl: 'https://promptpilot.app',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 30 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },
  {
    slug: 'translatenow-neural',
    canonicalDomain: 'translatenow.io',
    name: 'TranslateNow Neural',
    tagline: 'Contextual software localization with code-syntax protection',
    description: 'Localize i18n JSON files while preserving React JSX variables, markdown links, and template literals accurately.',
    websiteUrl: 'https://translatenow.io',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 12,
  },
  {
    slug: 'smartmock-ai',
    canonicalDomain: 'smartmock.design',
    name: 'SmartMock AI',
    tagline: 'Instant 3D device mockups generated from raw website screenshots',
    description: 'Transform boring flat screenshots into photorealistic isometric renders and floating device mockups in seconds.',
    websiteUrl: 'https://smartmock.design',
    categorySlug: 'ai-tools',
    pricing: { model: 'freemium', startingPrice: 9 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 13,
  },
  {
    slug: 'fine-tune-studio',
    canonicalDomain: 'finetunestudio.ai',
    name: 'FineTune Studio',
    tagline: 'One-click LoRA fine-tuning for open-source Mistral and Llama models',
    description: 'Serverless training infrastructure with automatic dataset deduplication, validation curves, and GGUF quantization export.',
    websiteUrl: 'https://finetunestudio.ai',
    categorySlug: 'ai-tools',
    pricing: { model: 'paid', startingPrice: 79 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 14,
  },

  // ===================== AI AGENTS (13 Products) =====================
  {
    slug: 'agentforge',
    canonicalDomain: 'agentforge.dev',
    name: 'AgentForge',
    tagline: 'Autonomous multi-agent orchestration framework for production engineers',
    description: 'Build, debug, and monitor hierarchical multi-agent LLM systems with real-time token budgeting and deterministic state transitions.',
    websiteUrl: 'https://agentforge.dev',
    categorySlug: 'ai-agents',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 0,
  },
  {
    slug: 'devops-sentinel',
    canonicalDomain: 'devopssentinel.io',
    name: 'DevOps Sentinel',
    tagline: 'Autonomous SRE agent that debugs Kubernetes pod crashes and memory leaks',
    description: 'Analyzes cluster traces, predicts cascading outage points, and auto-submits isolated hotfix pull requests to resolve incidents.',
    websiteUrl: 'https://devopssentinel.io',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 99 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'outbound-sdr-bot',
    canonicalDomain: 'outboundsdr.ai',
    name: 'OutboundSDR AI',
    tagline: 'Autonomous sales prospecting agent that qualifies leads via LinkedIn and email',
    description: 'Researches company annual reports, identifies pain points, and crafts individualized multi-channel touchpoints with verified deliverability.',
    websiteUrl: 'https://outboundsdr.ai',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 149 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'browserclaw',
    canonicalDomain: 'browserclaw.com',
    name: 'BrowserClaw',
    tagline: 'Headless AI web agent that navigates complex dynamic web portals',
    description: 'Execute stateful web automation, fill multi-step forms, and bypass complex DOM changes without brittle CSS selectors.',
    websiteUrl: 'https://browserclaw.com',
    categorySlug: 'ai-agents',
    pricing: { model: 'freemium', startingPrice: 29 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'supportcrew-ai',
    canonicalDomain: 'supportcrew.co',
    name: 'SupportCrew AI',
    tagline: 'Self-improving tier-1 customer support agents with ticket resolution SLAs',
    description: 'Connects directly to Zendesk and Intercom. Resolves 68% of routine technical queries instantly using verified documentation.',
    websiteUrl: 'https://supportcrew.co',
    categorySlug: 'ai-agents',
    pricing: { model: 'freemium', startingPrice: 49 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'recruiterbot-pro',
    canonicalDomain: 'recruiterbot.tech',
    name: 'RecruiterBot Pro',
    tagline: 'Autonomous technical candidate sourcer and resume matcher',
    description: 'Analyzes GitHub repositories, technical blogs, and portfolio repositories to match engineering candidates to strict company rubrics.',
    websiteUrl: 'https://recruiterbot.tech',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 89 },
    logoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'marketscout-agent',
    canonicalDomain: 'marketscout.ai',
    name: 'MarketScout Agent',
    tagline: 'Track competitor pricing changes, roadmap leaks, and hiring moves in real-time',
    description: 'Autonomous competitive intelligence engine crawling public changelogs, patent filings, and glassdoor updates.',
    websiteUrl: 'https://marketscout.ai',
    categorySlug: 'ai-agents',
    pricing: { model: 'freemium', startingPrice: 39 },
    logoUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'financial-analyst-bot',
    canonicalDomain: 'finanalyst.io',
    name: 'FinAnalyst Bot',
    tagline: 'Autonomous SEC 10-K filing analyst and earnings call modeler',
    description: 'Instant financial statement decomposition with automated DCF modeling, margin decomposition, and debt covenant analysis.',
    websiteUrl: 'https://finanalyst.io',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 120 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'cyberdefense-agent',
    canonicalDomain: 'cyberdefense.dev',
    name: 'CyberDefense Agent',
    tagline: 'Continuous red-team penetration testing agent for cloud APIs',
    description: 'Automated vulnerability reconnaissance simulating real-world OWASP Top 10 attack paths and reporting zero-day exposures.',
    websiteUrl: 'https://cyberdefense.dev',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 199 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'codegenius-agent',
    canonicalDomain: 'codegenius.app',
    name: 'CodeGenius Agent',
    tagline: 'End-to-end bug fix agent that generates unit tests and pull requests',
    description: 'Give CodeGenius a Jira ticket and it clones your repo, reproduces the failure, writes reproduction tests, and submits a PR.',
    websiteUrl: 'https://codegenius.app',
    categorySlug: 'ai-agents',
    pricing: { model: 'freemium', startingPrice: 45 },
    logoUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'legalreview-agent',
    canonicalDomain: 'legalreview.ai',
    name: 'LegalReview Agent',
    tagline: 'Redline commercial SaaS vendor contracts and NDAs against company playbooks',
    description: 'Identifies non-standard indemnification clauses, governing law mismatches, and data ownership risks automatically.',
    websiteUrl: 'https://legalreview.ai',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 79 },
    logoUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'socialpulse-agent',
    canonicalDomain: 'socialpulse.io',
    name: 'SocialPulse Agent',
    tagline: 'Autonomous social media manager with brand voice alignment',
    description: 'Monitors industry conversations, writes authoritative replies, and schedules visual content across Twitter and LinkedIn.',
    websiteUrl: 'https://socialpulse.io',
    categorySlug: 'ai-agents',
    pricing: { model: 'freemium', startingPrice: 29 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },
  {
    slug: 'opsflow-autonomous',
    canonicalDomain: 'opsflow.cloud',
    name: 'OpsFlow Autonomous',
    tagline: 'Self-healing cloud infrastructure and resource autoscaler',
    description: 'Dynamically balances spot vs on-demand compute instances to reduce AWS and GCP cloud bills by up to 45%.',
    websiteUrl: 'https://opsflow.cloud',
    categorySlug: 'ai-agents',
    pricing: { model: 'paid', startingPrice: 60 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 12,
  },

  // ===================== DEVELOPER TOOLS (14 Products) =====================
  {
    slug: 'vectorpulse-cloud',
    canonicalDomain: 'vectorpulse.cloud',
    name: 'VectorPulse Cloud',
    tagline: 'Serverless vector database engine with automated sub-millisecond similarity indexing',
    description: 'Ultra-low latency vector embeddings storage built specifically for high-throughput LLM reasoning pipelines and autonomous agents.',
    websiteUrl: 'https://vectorpulse.cloud',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 0,
  },
  {
    slug: 'devsync-ai',
    canonicalDomain: 'devsync.ai',
    name: 'DevSync AI',
    tagline: 'Autonomous code review agent that spots performance regressions before merging',
    description: 'DevSync connects directly to your Git repositories, analyzing PR AST diffs and predicting bundle-size regressions and memory leaks.',
    websiteUrl: 'https://devsync.ai',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 0,
  },
  {
    slug: 'devflow',
    canonicalDomain: 'devflow.io',
    name: 'DevFlow',
    tagline: 'Automated PR review and preview environment manager',
    description: 'Spin up isolated preview environments for every pull request with zero configuration and automated security scanning.',
    websiteUrl: 'https://devflow.io',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 25 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'auditshield',
    canonicalDomain: 'auditshield.dev',
    name: 'AuditShield',
    tagline: 'Zero-trust API key scanner and cryptographic secret rotation service',
    description: 'Scans private git history and docker layers to identify leaked credentials and automate rotation across AWS, Stripe, and Sendgrid.',
    websiteUrl: 'https://auditshield.dev',
    categorySlug: 'developer-tools',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'schemapilot',
    canonicalDomain: 'schemapilot.dev',
    name: 'SchemaPilot',
    tagline: 'Database migration linter and non-blocking DDL generator',
    description: 'Validates Prisma and Mongoose schema changes for backward compatibility, preventing lock contention and table deadlocks in production.',
    websiteUrl: 'https://schemapilot.dev',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'fastdeploy-edge',
    canonicalDomain: 'fastdeploy.sh',
    name: 'FastDeploy Edge',
    tagline: 'Sub-second serverless micro-container deployments across global PoPs',
    description: 'Deploy Node.js and Rust microservices globally with instant cold-start times under 15ms and automated Anycast routing.',
    websiteUrl: 'https://fastdeploy.sh',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'mockforge',
    canonicalDomain: 'mockforge.io',
    name: 'MockForge',
    tagline: 'Zero-config mock REST and GraphQL servers for frontend teams',
    description: 'Generate realistic stateful mock APIs with dynamic delay simulation, error rate injection, and OpenAPI 3.0 export.',
    websiteUrl: 'https://mockforge.io',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 12 },
    logoUrl: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'bundleguard',
    canonicalDomain: 'bundleguard.dev',
    name: 'BundleGuard',
    tagline: 'Automated JavaScript bundle size regression monitor for Next.js',
    description: 'Catches bloated dependencies and accidental lodash imports directly in GitHub pull request status checks.',
    websiteUrl: 'https://bundleguard.dev',
    categorySlug: 'developer-tools',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'cacheflow-redis',
    canonicalDomain: 'cacheflow.dev',
    name: 'CacheFlow Redis',
    tagline: 'Intelligent multi-tier cache invalidation framework for distributed systems',
    description: 'Eliminates cache thundering herds and stale reads using distributed stampede locks and stale-while-revalidate guarantees.',
    websiteUrl: 'https://cacheflow.dev',
    categorySlug: 'developer-tools',
    pricing: { model: 'paid', startingPrice: 39 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'loglens-analytics',
    canonicalDomain: 'loglens.io',
    name: 'LogLens Analytics',
    tagline: 'High-throughput structured log parser with ClickHouse backplane',
    description: 'Ingest 50,000 logs/sec with full-text search, anomaly detection alerts, and zero indexing lag.',
    websiteUrl: 'https://loglens.io',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 45 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'api-inspector',
    canonicalDomain: 'apiinspector.dev',
    name: 'API Inspector',
    tagline: 'Live webhook debugger and HTTP payload capture tunnel',
    description: 'Capture, replay, and inspect incoming third-party webhooks with zero local software installations.',
    websiteUrl: 'https://apiinspector.dev',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 10 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'prisma-visualizer',
    canonicalDomain: 'prismavis.dev',
    name: 'Prisma Visualizer',
    tagline: 'Interactive ER diagrams and query performance profiler for Prisma ORM',
    description: 'Spot N+1 relation queries and inspect complex multi-table joins visually from your Prisma schema.',
    websiteUrl: 'https://prismavis.dev',
    categorySlug: 'developer-tools',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'grpc-studio',
    canonicalDomain: 'grpcstudio.io',
    name: 'gRPC Studio',
    tagline: 'Postman-style GUI client for testing high-performance protobuf APIs',
    description: 'Supports bidirectional streaming, dynamic proto reflection, and automated load benchmarking for gRPC services.',
    websiteUrl: 'https://grpcstudio.io',
    categorySlug: 'developer-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },
  {
    slug: 'gitpulse-insights',
    canonicalDomain: 'gitpulse.co',
    name: 'GitPulse Insights',
    tagline: 'Engineering team velocity metrics and burnout risk indicators',
    description: 'Data-driven DORA metrics, PR turnaround times, and developer flow-state analytics without intrusive surveillance.',
    websiteUrl: 'https://gitpulse.co',
    categorySlug: 'developer-tools',
    pricing: { model: 'paid', startingPrice: 50 },
    logoUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 12,
  },

  // ===================== SAAS & ENTERPRISE (14 Products) =====================
  {
    slug: 'supasite',
    canonicalDomain: 'getsupasite.com',
    name: 'Supasite',
    tagline: 'AI-powered static site builder with instant edge deployments',
    description: 'Supasite analyzes your repository or prompt to generate production-ready Next.js landing pages deployed across 300+ edge locations.',
    websiteUrl: 'https://getsupasite.com',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 0,
  },
  {
    slug: 'teamsync-cloud',
    canonicalDomain: 'teamsync.cloud',
    name: 'TeamSync Cloud',
    tagline: 'Asynchronous standup and sprint alignment workspace for remote engineering teams',
    description: 'Eliminate 30-minute daily zoom standups with structured blockers reporting, Jira sync, and AI progress recaps.',
    websiteUrl: 'https://teamsync.cloud',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 8 },
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'churnradar',
    canonicalDomain: 'churnradar.io',
    name: 'ChurnRadar',
    tagline: 'Predictive customer churn detection and account retention automation',
    description: 'Monitors product usage drops and billing hesitation signals to trigger tailored customer success interventions.',
    websiteUrl: 'https://churnradar.io',
    categorySlug: 'saas',
    pricing: { model: 'paid', startingPrice: 79 },
    logoUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'billingflow-paddle',
    canonicalDomain: 'billingflow.io',
    name: 'BillingFlow',
    tagline: 'Self-serve customer billing portal and invoice reconciler for Paddle and Stripe',
    description: 'Embeddable customer subscription management widget supporting prorations, tax exemptions, and payment method updates.',
    websiteUrl: 'https://billingflow.io',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 29 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'userpilot-insights',
    canonicalDomain: 'userinsights.co',
    name: 'UserInsights',
    tagline: 'Frictionless in-app micro-surveys and CSAT telemetry widgets',
    description: 'Capture qualitative feedback at critical conversion moments without interrupting the core user experience.',
    websiteUrl: 'https://userinsights.co',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'featureboard-hq',
    canonicalDomain: 'featureboard.app',
    name: 'FeatureBoard HQ',
    tagline: 'Public product roadmap and feature upvoting portal for SaaS founders',
    description: 'Prioritize customer feature requests, close feedback loops, and publish automated release changelogs.',
    websiteUrl: 'https://featureboard.app',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 24 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'contractnest',
    canonicalDomain: 'contractnest.com',
    name: 'ContractNest',
    tagline: 'Lightweight electronic signatures and PDF audit certificates',
    description: 'Compliant ESIGN and eIDAS electronic signature platform designed for agile startup sales teams.',
    websiteUrl: 'https://contractnest.com',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'statusguard-pro',
    canonicalDomain: 'statusguard.io',
    name: 'StatusGuard Pro',
    tagline: 'Public status pages with multi-channel incident subscriber broadcasting',
    description: 'Keep customers informed during outages with automated SMS, email, and Discord status broadcast updates.',
    websiteUrl: 'https://statusguard.io',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 20 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'affiliatetrack-saas',
    canonicalDomain: 'affiliatetrack.co',
    name: 'AffiliateTrack',
    tagline: 'Cookie-less referral and partner commission engine for B2B SaaS',
    description: 'Launch an automated affiliate program with instant Stripe Connect payouts and verified domain attribution.',
    websiteUrl: 'https://affiliatetrack.co',
    categorySlug: 'saas',
    pricing: { model: 'paid', startingPrice: 49 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'supportdesk-hq',
    canonicalDomain: 'supportdeskhq.com',
    name: 'SupportDesk HQ',
    tagline: 'Shared email inbox for startup co-founders and support teams',
    description: 'Never collide on customer support replies with collision detection, internal notes, and email assignees.',
    websiteUrl: 'https://supportdeskhq.com',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 12 },
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'cloudspend-optimizer',
    canonicalDomain: 'cloudspend.app',
    name: 'CloudSpend Optimizer',
    tagline: 'Identify abandoned AWS RDS snapshots and idle load balancers',
    description: 'Instant read-only AWS IAM assessment that points out unattached EBS volumes and over-provisioned ECS tasks.',
    websiteUrl: 'https://cloudspend.app',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 39 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'documate-esign',
    canonicalDomain: 'documate.io',
    name: 'DocuMate eSign',
    tagline: 'API-first document generation and template autofill',
    description: 'Convert webhooks directly into watermarked, legally binding PDF contracts with dynamic merge fields.',
    websiteUrl: 'https://documate.io',
    categorySlug: 'saas',
    pricing: { model: 'freemium', startingPrice: 25 },
    logoUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },
  {
    slug: 'revshare-engine',
    canonicalDomain: 'revshare.dev',
    name: 'RevShare Engine',
    tagline: 'Automated marketplace vendor payout splits and tax withholding',
    description: 'Multi-party payment splits engine for platforms, courses, and digital marketplace creator economies.',
    websiteUrl: 'https://revshare.dev',
    categorySlug: 'saas',
    pricing: { model: 'paid', startingPrice: 89 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 12,
  },
  {
    slug: 'complianceguard-soc2',
    canonicalDomain: 'complianceguard.co',
    name: 'ComplianceGuard',
    tagline: 'Continuous SOC2 and ISO27001 automated compliance telemetry',
    description: 'Integrates with GitHub, Google Workspace, and AWS to verify evidence collection for annual audits.',
    websiteUrl: 'https://complianceguard.co',
    categorySlug: 'saas',
    pricing: { model: 'paid', startingPrice: 199 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 13,
  },

  // ===================== PRODUCTIVITY (12 Products) =====================
  {
    slug: 'focusos-app',
    canonicalDomain: 'focusos.app',
    name: 'FocusOS',
    tagline: 'Distraction-free desktop workspace that blocks attention-hijacking feeds',
    description: 'Deep-work session manager with ambient binaural soundscapes, strict domain blockers, and Pomodoro telemetry.',
    websiteUrl: 'https://focusos.app',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 8 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'notionsprint',
    canonicalDomain: 'notionsprint.com',
    name: 'NotionSprint',
    tagline: 'Two-way synchronization between Notion tasks and GitHub Issues',
    description: 'Keeps non-technical product managers and GitHub-centric software developers in sync automatically.',
    websiteUrl: 'https://notionsprint.com',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 10 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'tabmaster-pro',
    canonicalDomain: 'tabmaster.dev',
    name: 'TabMaster Pro',
    tagline: 'Intelligent browser tab suspender and session organizer',
    description: 'Reduces Chrome memory consumption by up to 80% by suspending inactive tabs into organized searchable workspaces.',
    websiteUrl: 'https://tabmaster.dev',
    categorySlug: 'productivity',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'quickdraft-markdown',
    canonicalDomain: 'quickdraft.io',
    name: 'QuickDraft',
    tagline: 'Instant markdown scratchpad with local encryption and Git syncing',
    description: 'Blazing fast plain-text editor with instant command palette, LaTeX math rendering, and offline-first storage.',
    websiteUrl: 'https://quickdraft.io',
    categorySlug: 'productivity',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'calflow-calendar',
    canonicalDomain: 'calflow.app',
    name: 'CalFlow',
    tagline: 'Modern booking link with round-robin team scheduling and time-zone math',
    description: 'Fast, clutter-free alternative to Calendly with instant Google and Outlook calendar integration.',
    websiteUrl: 'https://calflow.app',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 12 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'snippetsync-cli',
    canonicalDomain: 'snippetsync.dev',
    name: 'SnippetSync',
    tagline: 'Cross-IDE code snippet vault shared across your engineering team',
    description: 'Sync reusable boilerplate and shell commands across VS Code, JetBrains, and terminal terminals seamlessly.',
    websiteUrl: 'https://snippetsync.dev',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 5 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'meetingrecap-ai',
    canonicalDomain: 'meetingrecap.io',
    name: 'MeetingRecap AI',
    tagline: 'Zero-bot silent audio transcription and action-item distributor',
    description: 'Captures desktop audio directly without awkward bots joining your call, generating structured summaries instantly.',
    websiteUrl: 'https://meetingrecap.io',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'inboxzen-cleaner',
    canonicalDomain: 'inboxzen.co',
    name: 'InboxZen',
    tagline: '1-click newsletter unsubscription and promotional email quarantine',
    description: 'Safely rolls up marketing spam into a single daily briefing email while protecting your primary inbox.',
    websiteUrl: 'https://inboxzen.co',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 7 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'workspacemenu-mac',
    canonicalDomain: 'workspacemenu.com',
    name: 'WorkspaceMenu',
    tagline: 'macOS menu bar utility for launching development projects and staging URLs',
    description: 'Switch between client projects, Docker stacks, and Figma files with a single global keyboard shortcut.',
    websiteUrl: 'https://workspacemenu.com',
    categorySlug: 'productivity',
    pricing: { model: 'paid', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'timetrack-nano',
    canonicalDomain: 'timetracknano.app',
    name: 'TimeTrack Nano',
    tagline: 'Invisible automatic project time tracking based on active git branch',
    description: 'Never forget to log billable client hours again. Detects active VS Code windows and git repository commits.',
    websiteUrl: 'https://timetracknano.app',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 9 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'audiocopy-dictate',
    canonicalDomain: 'audiocopy.dev',
    name: 'AudioCopy Dictate',
    tagline: 'Instant global voice-to-text dictation across every desktop text field',
    description: 'Press F8, speak naturally, and watch accurate technical punctuation and code snippets typed out instantly.',
    websiteUrl: 'https://audiocopy.dev',
    categorySlug: 'productivity',
    pricing: { model: 'freemium', startingPrice: 14 },
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },
  {
    slug: 'zenread-reader',
    canonicalDomain: 'zenread.app',
    name: 'ZenRead',
    tagline: 'Distraction-free web article reader with EPUB export and Kindle sync',
    description: 'Strips out popups, cookie consent overlays, and auto-playing ads, rendering articles in readable serif typography.',
    websiteUrl: 'https://zenread.app',
    categorySlug: 'productivity',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 12,
  },

  // ===================== MARKETING TOOLS (11 Products) =====================
  {
    slug: 'viralpulse-social',
    canonicalDomain: 'viralpulse.io',
    name: 'ViralPulse',
    tagline: 'AI hook generator and virality scoring for Twitter/X threads',
    description: 'Trained on 10,000+ top-performing startup founder threads to optimize hooks, formatting, and reader retention.',
    websiteUrl: 'https://viralpulse.io',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'copycraft-ai',
    canonicalDomain: 'copycraft.app',
    name: 'CopyCraft AI',
    tagline: 'High-conversion headline generator tailored to B2B software buyer personas',
    description: 'Generate value-proposition headlines, feature benefit bullets, and hero section copy that passes the 5-second test.',
    websiteUrl: 'https://copycraft.app',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 24 },
    logoUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'growthloop-attribution',
    canonicalDomain: 'growthloop.io',
    name: 'GrowthLoop',
    tagline: 'First-party multi-touch marketing attribution without privacy cookie loss',
    description: 'Trace customer signups back to exact organic newsletter mentions, podcast sponsors, and Reddit conversations.',
    websiteUrl: 'https://growthloop.io',
    categorySlug: 'marketing-tools',
    pricing: { model: 'paid', startingPrice: 79 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'testimonialhub',
    canonicalDomain: 'testimonialhub.co',
    name: 'TestimonialHub',
    tagline: 'Collect video testimonials and customer quotes with embeddable social proof walls',
    description: 'Automated video recording forms, transcription, and interactive wall of love widgets for high-converting landing pages.',
    websiteUrl: 'https://testimonialhub.co',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'adcreative-generator',
    canonicalDomain: 'adcreative.tech',
    name: 'AdCreative Generator',
    tagline: 'Batch generate 50+ banner ad variants for Meta, Google, and LinkedIn',
    description: 'Enter your brand colors and target headline to auto-generate conversion-tested aspect ratios and layout variants.',
    websiteUrl: 'https://adcreative.tech',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 29 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'emailpreview-tester',
    canonicalDomain: 'emailpreview.dev',
    name: 'EmailPreview Tester',
    tagline: 'Preview HTML newsletters across 40+ email clients and dark mode settings',
    description: 'Catches broken Outlook table rendering, missing alt tags, and dark-mode color inversions before hitting send.',
    websiteUrl: 'https://emailpreview.dev',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'coldreach-verifier',
    canonicalDomain: 'coldreach.io',
    name: 'ColdReach Verifier',
    tagline: 'Real-time SMTP ping and disposable mailbox verification API',
    description: 'Keep email bounce rates under 1.5% with MX record inspection, catch-all server detection, and syntax validation.',
    websiteUrl: 'https://coldreach.io',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'launchblast-press',
    canonicalDomain: 'launchblast.press',
    name: 'LaunchBlast Press',
    tagline: 'Distribute your startup launch to 150+ technology journalists and newsletters',
    description: 'Verified media contact database with personalized pitch suggestions and real-time open-rate tracking.',
    websiteUrl: 'https://launchblast.press',
    categorySlug: 'marketing-tools',
    pricing: { model: 'paid', startingPrice: 99 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'qrflow-dynamic',
    canonicalDomain: 'qrflow.app',
    name: 'QRFlow Dynamic',
    tagline: 'Branded dynamic QR codes with destination routing and scan analytics',
    description: 'Update redirect destinations after printing event brochures and track scan location demographics in real-time.',
    websiteUrl: 'https://qrflow.app',
    categorySlug: 'marketing-tools',
    pricing: { model: 'freemium', startingPrice: 8 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'churnwinback-ai',
    canonicalDomain: 'churnwinback.com',
    name: 'ChurnWinBack AI',
    tagline: 'Automated exit surveys and win-back discount sequences for canceled subscribers',
    description: 'Recover up to 14% of churned SaaS accounts with personalized founder discount emails and roadmap previews.',
    websiteUrl: 'https://churnwinback.com',
    categorySlug: 'marketing-tools',
    pricing: { model: 'paid', startingPrice: 45 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'influencerfind-ai',
    canonicalDomain: 'influencerfind.co',
    name: 'InfluencerFind',
    tagline: 'Discover high-engagement niche tech creators on YouTube and X',
    description: 'Filter technology influencers by true engagement rate, audience seniority, and verified sponsor history.',
    websiteUrl: 'https://influencerfind.co',
    categorySlug: 'marketing-tools',
    pricing: { model: 'paid', startingPrice: 69 },
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },

  // ===================== SEO TOOLS (11 Products) =====================
  {
    slug: 'hypermetric-seo',
    canonicalDomain: 'hypermetric.seo',
    name: 'HyperMetric SEO',
    tagline: 'Programmatic SEO architecture and keyword cannibalization detector',
    description: 'Find untapped long-tail keyword clusters, audit internal link graphs, and catch ranking cannibalization before Google drops traffic.',
    websiteUrl: 'https://hypermetric.seo',
    categorySlug: 'seo-tools',
    pricing: { model: 'freemium', startingPrice: 39 },
    logoUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'backlinkradar-pro',
    canonicalDomain: 'backlinkradar.io',
    name: 'BacklinkRadar',
    tagline: 'Instant alerts when competitors earn new high-authority editorial backlinks',
    description: 'Monitors web crawler graphs daily to identify competitor digital PR mentions and broken link opportunity outreach.',
    websiteUrl: 'https://backlinkradar.io',
    categorySlug: 'seo-tools',
    pricing: { model: 'paid', startingPrice: 59 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'serppulse-tracker',
    canonicalDomain: 'serppulse.dev',
    name: 'SERPPulse Tracker',
    tagline: 'Daily rank tracking across 120+ countries and mobile viewport layouts',
    description: 'Track daily Google search rankings with pixel-accurate SERP feature detection (snippets, PAA, video carousels).',
    websiteUrl: 'https://serppulse.dev',
    categorySlug: 'seo-tools',
    pricing: { model: 'freemium', startingPrice: 20 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'schemawriter-pro',
    canonicalDomain: 'schemawriter.app',
    name: 'SchemaWriter Pro',
    tagline: 'Generate rich-snippet JSON-LD structured data with zero markup errors',
    description: 'Visual generator for SoftwareApplication, FAQPage, Article, and Product schema validated against Google Rich Results standards.',
    websiteUrl: 'https://schemawriter.app',
    categorySlug: 'seo-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'contentgap-finder',
    canonicalDomain: 'contentgap.co',
    name: 'ContentGap Finder',
    tagline: 'Discover topic clusters your competitors rank for that your site misses',
    description: 'Compares top 10 search results for a primary keyword to identify missing subheadings and semantic questions.',
    websiteUrl: 'https://contentgap.co',
    categorySlug: 'seo-tools',
    pricing: { model: 'freemium', startingPrice: 29 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'canonicalcheck-ai',
    canonicalDomain: 'canonicalcheck.dev',
    name: 'CanonicalCheck AI',
    tagline: 'Audit hreflang tags, canonical redirects, and trailing slash crawl bloat',
    description: 'Crawl up to 50,000 pages to catch duplicate content penalties and misconfigured index meta tags.',
    websiteUrl: 'https://canonicalcheck.dev',
    categorySlug: 'seo-tools',
    pricing: { model: 'open_source', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'anchorcloud-audit',
    canonicalDomain: 'anchorcloud.io',
    name: 'AnchorCloud Audit',
    tagline: 'Audit backlink anchor text distribution and disavow toxic spam links',
    description: 'Ensure natural anchor ratios and generate Google Search Console disavow files in one click.',
    websiteUrl: 'https://anchorcloud.io',
    categorySlug: 'seo-tools',
    pricing: { model: 'freemium', startingPrice: 19 },
    logoUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'titlesplit-test',
    canonicalDomain: 'titlesplit.app',
    name: 'TitleSplit Test',
    tagline: 'Automated SEO meta title and description A/B testing on Google SERPs',
    description: 'Rotate search snippets periodically to statistically measure click-through rate (CTR) gains in Google Search Console.',
    websiteUrl: 'https://titlesplit.app',
    categorySlug: 'seo-tools',
    pricing: { model: 'paid', startingPrice: 45 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'indexnow-fast',
    canonicalDomain: 'indexnowfast.dev',
    name: 'IndexNow Fast',
    tagline: 'Instant real-time URL indexing ping to Bing, Yandex, and IndexNow engines',
    description: 'Notify search engines immediately when new software launches or documentation updates are published.',
    websiteUrl: 'https://indexnowfast.dev',
    categorySlug: 'seo-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'corevitals-monitor',
    canonicalDomain: 'corevitals.tech',
    name: 'CoreVitals Monitor',
    tagline: 'Continuous field data monitoring for LCP, INP, and CLS performance',
    description: 'Real user metrics (RUM) tracking with detailed element attribution for slow interaction to next paint (INP).',
    websiteUrl: 'https://corevitals.tech',
    categorySlug: 'seo-tools',
    pricing: { model: 'freemium', startingPrice: 25 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
  {
    slug: 'internallink-genius',
    canonicalDomain: 'internallink.io',
    name: 'InternalLink Genius',
    tagline: 'Automated internal linking recommendations based on semantic page embeddings',
    description: 'Find relevant contextual anchor opportunities across hundreds of blog posts to pass PageRank to money pages.',
    websiteUrl: 'https://internallink.io',
    categorySlug: 'seo-tools',
    pricing: { model: 'freemium', startingPrice: 35 },
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 11,
  },

  // ===================== DESIGN TOOLS (11 Products) =====================
  {
    slug: 'shipfast-ui',
    canonicalDomain: 'shipfastui.com',
    name: 'ShipFast UI',
    tagline: 'Accessible React & Tailwind component library for hyper-growth SaaS platforms',
    description: 'Over 120+ meticulously crafted, conversion-optimized SaaS components with dark mode, full keyboard navigation, and Figma tokens.',
    websiteUrl: 'https://shipfastui.com',
    categorySlug: 'design-tools',
    pricing: { model: 'paid', startingPrice: 49 },
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 0,
  },
  {
    slug: 'canvasflow-vector',
    canonicalDomain: 'canvasflow.design',
    name: 'CanvasFlow Vector',
    tagline: 'Browser-based SVG vector editor with real-time multiplayer collaboration',
    description: 'Ultra-fast vector graphics software supporting boolean path operations, component variants, and clean CSS code export.',
    websiteUrl: 'https://canvasflow.design',
    categorySlug: 'design-tools',
    pricing: { model: 'freemium', startingPrice: 15 },
    logoUrl: 'https://images.unsplash.com/photo-1620641788421-7a1c342ea42e?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 1,
  },
  {
    slug: 'paletteai-generator',
    canonicalDomain: 'paletteai.co',
    name: 'PaletteAI',
    tagline: 'Harmonious color palettes with automatic WCAG 2.2 AA contrast compliance',
    description: 'Generate semantic Tailwind tokens and CSS custom properties guaranteed to meet accessibility contrast standards.',
    websiteUrl: 'https://paletteai.co',
    categorySlug: 'design-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 2,
  },
  {
    slug: 'mockupstudio-3d',
    canonicalDomain: 'mockupstudio.app',
    name: 'MockupStudio 3D',
    tagline: 'Render device mockups in WebGL with customizable studio lighting',
    description: 'Create interactive 3D product previews for laptops, iPhones, and tablets with animated camera orbit paths.',
    websiteUrl: 'https://mockupstudio.app',
    categorySlug: 'design-tools',
    pricing: { model: 'freemium', startingPrice: 20 },
    logoUrl: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 3,
  },
  {
    slug: 'iconcrafter-pro',
    canonicalDomain: 'iconcrafter.io',
    name: 'IconCrafter Pro',
    tagline: 'Consistent 24px Lucide and Feather style vector icon generator',
    description: 'Generate custom stroke icons that perfectly match your design system geometry and line weights.',
    websiteUrl: 'https://iconcrafter.io',
    categorySlug: 'design-tools',
    pricing: { model: 'freemium', startingPrice: 12 },
    logoUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 4,
  },
  {
    slug: 'figmatocode-turbo',
    canonicalDomain: 'figmatocode.dev',
    name: 'FigmaToCode Turbo',
    tagline: 'Export Figma frames directly to pixel-perfect Next.js Tailwind components',
    description: 'Clean, idiomatic TypeScript and Tailwind CSS code with responsive breakpoints and auto-layout preservation.',
    websiteUrl: 'https://figmatocode.dev',
    categorySlug: 'design-tools',
    pricing: { model: 'freemium', startingPrice: 25 },
    logoUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 5,
  },
  {
    slug: 'brandkit-gen',
    canonicalDomain: 'brandkitgen.com',
    name: 'BrandKit Gen',
    tagline: 'One-click favicon, app icon, and social preview generator for web apps',
    description: 'Upload one SVG logo and instantly download all standard web, iOS, Android, and Windows manifest icon sizes.',
    websiteUrl: 'https://brandkitgen.com',
    categorySlug: 'design-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1450133064473-71024230f91b?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 6,
  },
  {
    slug: 'gradientlab-css',
    canonicalDomain: 'gradientlab.dev',
    name: 'GradientLab CSS',
    tagline: 'Mesh gradients and glassmorphism backdrop effects for modern web apps',
    description: 'Interactive shader and multi-stop gradient composer with clean CSS radial-gradient output and Tailwind utility classes.',
    websiteUrl: 'https://gradientlab.dev',
    categorySlug: 'design-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 7,
  },
  {
    slug: 'fontpairing-pro',
    canonicalDomain: 'fontpairing.io',
    name: 'FontPairing Pro',
    tagline: 'Curated Google Font combinations with responsive scale calculations',
    description: 'Preview typography pairings across real marketing headlines, subheads, and body copy in light and dark mode.',
    websiteUrl: 'https://fontpairing.io',
    categorySlug: 'design-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1497633762265-9d179a990aa6?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 8,
  },
  {
    slug: 'contrastchecker-aa',
    canonicalDomain: 'contrastchecker.dev',
    name: 'ContrastChecker AA',
    tagline: 'Automated WCAG 2.2 color contrast ratio auditor for Figma design files',
    description: 'Scans your entire Figma design file for low-contrast text elements and suggests the nearest passing color shade.',
    websiteUrl: 'https://contrastchecker.dev',
    categorySlug: 'design-tools',
    pricing: { model: 'free', startingPrice: 0 },
    logoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 9,
  },
  {
    slug: 'wireflow-diagrams',
    canonicalDomain: 'wireflow.design',
    name: 'WireFlow Diagrams',
    tagline: 'Hand-drawn style architecture and user journey diagramming tool',
    description: 'Create technical system diagrams, database architectures, and UI flows with rapid keyboard shortcuts.',
    websiteUrl: 'https://wireflow.design',
    categorySlug: 'design-tools',
    pricing: { model: 'freemium', startingPrice: 10 },
    logoUrl: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=128&auto=format&fit=crop&q=80',
    screenshotUrls: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&auto=format&fit=crop&q=80'],
    daysAgo: 10,
  },
];

export async function seed100Products(): Promise<{ seededCount: number }> {
  await connectDB();
  logger.info(`Starting 100 Curated Cold-Start Supply Seeding...`);

  // 1. Fetch categories
  const categories = await Category.find({}).lean();
  const categoryMap = new Map<string, Types.ObjectId>();
  for (const cat of categories) {
    categoryMap.set(cat.slug, cat._id as Types.ObjectId);
  }

  // 2. Fetch default founder
  const founder = await User.findOne({ role: 'FOUNDER' }).lean();
  const defaultFounderId = founder?._id || new Types.ObjectId();

  let count = 0;
  for (const item of CURATED_100_PRODUCTS) {
    const catId = categoryMap.get(item.categorySlug) || Array.from(categoryMap.values())[0];
    const launchDate = new Date(Date.now() - item.daysAgo * 24 * 60 * 60 * 1000);

    await Product.findOneAndUpdate(
      { slug: item.slug },
      {
        $set: {
          slug: item.slug,
          canonicalDomain: item.canonicalDomain,
          name: item.name,
          tagline: item.tagline,
          description: item.description,
          websiteUrl: item.websiteUrl,
          founderId: defaultFounderId,
          submittedById: defaultFounderId,
          categoryId: catId,
          pricing: item.pricing,
          media: {
            logoUrl: item.logoUrl,
            screenshotUrls: item.screenshotUrls,
          },
          status: ProductStatus.LIVE,
          launchDate,
          initialVersion: 1,
          updatedAt: new Date(),
        },
        $setOnInsert: {
          createdAt: launchDate,
        },
      },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    count++;
  }

  // 3. Recalculate product counts for each category
  for (const [slug, catId] of categoryMap.entries()) {
    const total = await Product.countDocuments({ categoryId: catId, status: ProductStatus.LIVE });
    await Category.findByIdAndUpdate(catId, { $set: { productCount: total } });
  }

  logger.info(`✓ Successfully seeded ${count} cold-start curated products into MongoDB Atlas!`);
  return { seededCount: count };
}

if (require.main === module) {
  seed100Products()
    .then((res) => {
      console.log('✅ Cold-Start Supply Seeding Finished:', res);
      process.exit(0);
    })
    .catch((err) => {
      console.error('❌ Seeding failed:', err);
      process.exit(1);
    });
}

export default seed100Products;
